### PR TITLE
Fixes #74 - Set Content-Type for Execute, DescribeProcess and GetCapa…

### LINKED ISSUE #74: Incorrect ContentType is returned for WPS requests
### To reproduce

Perform a DecsribeProcess, GetCapabilities, or Execute request

### What happens

Get ContentType of 'application/json' returned

### What I expect to happen 

Get ContentType of 'application/xml' returned

### PR DESCRIPTION
**Pull request by jonescc**
…bilities responses

For WPS requests the response should currently always be of mimetype application/xml.

### CODE REVIEW

File: request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java [hunk 1]
```diff
@@ -31,6 +31,7 @@ public AwsApiResponse handleRequest(AwsApiRequest request, Context context) {
             //  Send caller a WPS error response
             AwsApiResponse.ResponseBuilder responseBuilder = new AwsApiResponse.ResponseBuilder();
             responseBuilder.statusCode(500);
+            responseBuilder.header("Content-Type", "application/xml");
```
Comment (akashisama) [inline request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java]: Why does this class exist isn't it doing exactly the same thing as its parent?

Comment (jonescc) [reply request-handler/src/main/java/au/org/aodn/aws/wps/lambda/WpsLambdaRequestHandler.java]: Yes, doesn't look to be doing anything extra anymore.  Not related to the change I was doing but happy to remove it to clean up the code a bit.

**Comment by jonescc** [comment]
@akashisama, have removed unused code.
