### PR TITLE
Fixes #143

### LINKED ISSUE #143: Timeseries in descending rather than ascending order
### To reproduce

Request a timeseries

### What happens 

Timeseries is in descending order

### What I expect to happen

Timeseries is in ascending order.   This matches the current production ordering and while the other order is valid, ascending is preferred by @ggalibert

### PR DESCRIPTION
**Pull request by jonescc**
Retrieve urls in ascending order

### CODE REVIEW

File: integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java [hunk 1]
```diff
@@ -166,7 +166,7 @@ public void testTimeseriesInTimestampOrder() {
 
         //  First line is CSV header
         //  Time field is index 0
-        //  Check that the timestamps are in descending time order
+        //  Check that the timestamps are in asscending time order
```
Comment (bhasin85) [inline integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java]: Funny typo 
giphy

Comment (jonescc) [reply integration-testing/src/test/java/au/org/emii/wps/it/ExecuteIT.java]: OK, fixed
